### PR TITLE
New metadata keywords

### PR DESCRIPTION
**Pull request by ismailsunni**
Update some keywords file to use new metadata. It's used for my PR related new_metadata_keywords

### CODE REVIEW

**Comment by akbargumbira** [comment]
Don't merge this yet until we release 3.1

**Comment by ismailsunni** [comment]
yes, I won't merge this one until I merge my new_metadata_keywords is finished in inasafe repo.

**Comment by lucernae** [comment]
So we still have test data in here?

**Comment by ismailsunni** [comment]
@lucernae yes, of course, I want to do it also. But, there are still some test that use this data, and I need to make it pass. In case we still don't use simple data for all test, I will merge this PR. Later. After I finished everything.

**Pull request merged**
